# Base layer
FROM node:18

# Set the working directory
WORKDIR /app

# Copy over dependency files
COPY package.json ./
COPY package-lock.json ./

# Install
RUN npm install

# Copy all files
COPY . .

CMD ["npm", "run", "start"]
