# docker-compose.yml

version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  xrpl-backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment: ['XRPL_CLIENT=${XRPL_CLIENT}']
    depends_on:
      db:
        condition: service_healthy
    command: ['node', 'main.js']
    networks:
      - default
