services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  database:

networks:
  default: